### ISSUE TITLE
臭うコード

### ISSUE THREAD

**Issue by YuyaAizawa** [tklab-group/JISDLab#1]
## 静的な型を利用する

package名，class名の組のclassにするとよさそうです．

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/util/Name.java#L40

## ユーティリティクラス

util のクラスは final とし，念のためコンストラクタをつぶしておくとよいです．

例
```java
public final class SampleUtil {
    private SampleUtil() {}
    
    public static Foo bar() {
        ...
    }
}
```

実はstaticしかないのでユーティリティにできる

- jisd.probej.Parser
- jisd.analysis.JarFileLoader

## enumを利用

種別は int でなく enum が適当です．

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/SrtVal.java#L23

## 既存のAPIが存在

- java.util.stream.Collectors#toListの内部実装がArrayListなので不要かと思います

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/util/Stream.java#L15

- System.getProperty("path.separator") があります

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/util/JISDPreProcess.java#L44

## byte配列からStringへ変換

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/util/Print.java#L19

```java
byte[] array = new byte[b.remaining()];
b.get(array);
return new String(array);
```

## defaultは例外とした方が安全

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/SrtVal.java#L85

```java
case 'V' :
    typename_tmp = "void";
    break;
default:
    throw new IllegalArgumentException("desc = "+desc);
```

## 要素がない場合の振る舞いがバラバラ

NoSuchElementException例外
https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/LinkedHashSetEx.java#L23

null
https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/LinkedHashSetEx.java#L34

## リソースが解放されない可能性

https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/JarFileLoader.java#L17

try-with-resourceを利用しましょう．
```java
try (JarFile jar = new JarFile("")) {
    jar.stream().forEach(z -> readJar(jar, z, cns));
}
```

## jisd.analysis.JarFileLoader

System.err に書き出さなくて大丈夫ですか？
https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/JarFileLoader.java#L31

不要です
https://github.com/tklab-group/JISDLab/blob/26ab53a415c6d7cf775484609281a7104e0792e2/JISD/src/jisd/analysis/JarFileLoader.java#L55

**Comment by sakupo** [comment]
- [ ] 静的な型を利用する
- [ ] ユーティリティクラス
- [ ] enumを利用
- [ ] 既存のAPIが存在
- [ ] byte配列からStringへ変換
- [ ] defaultは例外とした方が安全
- [ ] 要素がない場合の振る舞いがバラバラ
- [ ] リソースが解放されない可能性
- [ ] jisd.analysis.JarFileLoader
